series: Basic C++
title: References
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: A look at the confusing and often misunderstood world of references in C++.
language: C++
tags:
  - Core
extra_resources:
  - link: http://www.codeproject.com/Articles/13363/An-Insight-to-References-in-C
    title: Code Project: An Insight to References in C++ (Highly recommend reading)
  - link: http://stackoverflow.com/questions/752658/is-the-practice-of-returning-a-c-reference-variable-evil
    title: Stack Overflow: Is the practice of returning a C++ reference variable, evil?
connections:
  - series: Basic C++
    title: The Const Keyword